services:
    postgres:
        image: postgres
        restart: always
        environment: 
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: taskappdb
        ports:
            - "5432:5432"

    redis:
        image: redis:alpine
        restart: always
        ports: 
            - "6379:6379"
        
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        environment: 
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin